[package]
name = "ls-tiny"
version = "0.1.0"
authors = ["hibi221b"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
colored = "1.9.3"